In [5]:
import Leap, sys, time
from Leap import CircleGesture, KeyTapGesture, ScreenTapGesture, SwipeGesture
from ipywidgets import Text as TextWidget, Image as ImageWidget, HTML as HTMLWidget
from IPython.display import display
import numpy as np
import cv2
from PIL import Image as PIL_Image
from io import BytesIO
cv2.startWindowThread()

0

In [11]:
screen_xy =np.float32(
[ (606,179), (579,217), (552,258), (523,301), (491,349), (456,401),
  (660,201), (636,241), (611,282), (584,327), (554,377), (522,430),
  (717,224), (695,264), (672,307), (647,354), (619,404), (689,459),
  (773,247), (753,288), (732,332), (709,380), (683,432), (657,489),
  (830,272), (812,312), (794,358), (772,408), (750,462), (725,520),
  (888,296), (874,338), (856,386), (836,436), (816,492), (796,550),
  (948,320), (934,363), (920,412), (902,466), (885,522), (867,583),
 ])
screen_xy2 =np.float32(
[ (520,158),(498.5,193),(478,230), (456,268), (434,308), (412,348),
  (560,172), (540,210), (520,246), (500,285), (478,326), (456,366),
  (602,189), (582,226), (563,264), (544,304), (522,344), (501,386), 
  (644,206), (626,242), (606,281), (587,320), (566,362), (544,406),
  (686,222), (668,260), (650,299), (630,338), (611,380), (591,424),
  (729,239), (712,277), (694,317), (676,358), (656,398), (636,442),
  (772,256), (755,295), (738,334), (720,376), (702,417), (683,462),
 ])
screen_xy3 =np.float32(
[ (692,182), (677,239), (663,298), (648,358), (635,417), (621,479),
  (743,185), (729,244), (713,303), (700,365), (685,427), (671,492),
  (801,186), (784,247), (771,310), (755,375), (741,439), (727,505),
  (861,189), (845,252), (830,317), (816,384), (802,451), (786,521),
  (927,191), (911,258), (895,324), (880,393), (865,464), (851,536),
  (996,193), (981,263), (966,333), (951,405), (936,479), (921,554),
  (1073,195),(1058,268),(1043,342),(1027,417),(1013,494), (998,573),
 ])
screen_xy4 =np.float32(
[ (870,448), (885,539), (900,638), 
  (928,412), (948,508), (969,614),
  (999,370), (1024,474), (1050,586),
 ])
screen_xy5 =np.float32(
[ (248,113), (162,169), (78,227), 
  (289,191), (201,250), (113,309),
  (333,275), (242,335), (152,397),
 ])
obj_xyz = np.float32([ (i*24.8, j*25, 0) for j in range(7) for i in range(6)])
obj_xyz2 = np.float32([ (i*49.6, j*50, 0) for j in range(3) for i in range(3)])
retval, cm0, dist0, rvec, tvec = cv2.calibrateCamera([obj_xyz]*3+[obj_xyz2]*2, 
                                                   [screen_xy, screen_xy2, screen_xy3, screen_xy4, screen_xy5], 
                                                   (1280,720), None, None,
                    flags=cv2.CALIB_FIX_PRINCIPAL_POINT)
print(retval, cm0, dist0, rvec, tvec)

7.908430271818274 [[  1.24011990e+03   0.00000000e+00   6.40000000e+02]
 [  0.00000000e+00   1.21820836e+03   3.60000000e+02]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]] [[ 0.53627097 -1.63353802  0.02294884 -0.02049134  2.61696298]] [array([[ 1.41238852],
       [ 2.20001504],
       [-0.50500602]]), array([[ 1.60762266],
       [ 2.46759174],
       [-0.42296107]]), array([[-1.71440561],
       [-2.09565536],
       [ 0.80719681]]), array([[-1.89266848],
       [-1.34515711],
       [ 1.32288286]]), array([[-0.77111192],
       [-2.71827529],
       [ 0.44355385]])] [array([[ -15.31470185],
       [ -77.01938535],
       [ 506.49114598]]), array([[ -65.87798933],
       [-113.54390681],
       [ 681.46264923]]), array([[  20.72467455],
       [ -72.88646694],
       [ 496.52014266]]), array([[ 120.20585861],
       [  45.69334622],
       [ 658.57858744]]), array([[-183.06234879],
       [-120.56033444],
       [ 612.13151405]])]


In [12]:
def img_to_png(ima, cvt=None):
    if cvt:
        ima = cv2.cvtColor(ima, cvt)
    im = PIL_Image.fromarray(ima)
    bio = BytesIO()
    im.save(bio, format='png')
    return bio.getvalue()

In [13]:
controller = Leap.Controller()

In [14]:
test_pos=[(0.1+(1.0*i/4)*0.8,0.1+(1.0*j/2)*0.8) for i in range(5) for j in range(3)]

In [15]:
cm=None

In [14]:
# some inital parameters
cm=np.float32([[  1.25542912e+03,   0.00000000e+00,   6.39500000e+02],
       [  0.00000000e+00,   1.23283056e+03,   3.59500000e+02],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])
dist=np.float32([[ 0.54520465, -1.47166739,  0.02451086, -0.02110954,  1.96975927]])
tvec=[np.float32([[ 0.03590161],
       [-0.6163393 ],
       [-3.06629999]])]
rvec=[np.float32([[  -1.86198648],
       [ 262.13185195],
       [ 282.57265977]])]

In [6]:
# some initial paraeters
array = np.float32
cm=array([[  1.03861216e+03,   0.00000000e+00,   4.59025722e+02],
       [  0.00000000e+00,   1.00144358e+03,  -2.26439503e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])
dist=array([[ 0.10414326, -0.52876669, -0.01789585,  0.00671249,  0.25075185]])
tvec=[array([[-0.15562133],
       [-1.00533923],
       [-2.89834584]])]
rvec=[array([[  18.30289231],
       [ 322.14326406],
       [ 119.28120961]])]

In [20]:
result = []
screen_pos = []
cap = cv2.VideoCapture(0)
controller.set_policy_flags(Leap.Controller.POLICY_BACKGROUND_FRAMES)
txt = TextWidget()
#txt.set_css({"width":"800px"})
display(txt)
hand1txt = TextWidget()
#hand1txt.set_css({"width":"800px"})
display(hand1txt)
#img_widget = ImageWidget(width=600)
#display(img_widget)
idx = 0
while True:
    ret, img = cap.read()
    # img = cv2.resize(img, (960,540))
    H, W = img.shape[:2]
    #cv2.circle(img, (int(W*0.8), int(H*0.8)), 10, (0,0,255), -1)
    
    
    #img_widget.value = img_to_png(img, cvt=cv2.COLOR_BGR2RGB)
    frame = controller.frame()
    keycode = cv2.waitKey(1) & 0xff
        
    txt.value = "Frame id: %d, hands: %d, fingers: %d, tools: %d, gestures: %d" % (
              0, len(frame.hands), len(frame.fingers), len(frame.tools), len(frame.gestures()))
    tip = None
    if len(frame.hands)>0:
        hand1 = frame.hands[0]
        fingers = hand1.fingers.finger_type(1)
        if len(fingers):
            tip = fingers[0].tip_position
            tip_s="(%5.1f, %5.1f, %5.1f)"%(tip[0], tip[1], tip[2])
            #cv2.circle(img, (int(400-tip[0]*2), int(H-tip[1]*2)), 10, (0,0,255), -1)
            if cm is not None:
                xy = cv2.projectPoints(np.float32([(tip[0], tip[1], tip[2])]), rvec[0], tvec[0], cm, dist)[0][0][0]
                cv2.circle(img, (int(xy[0]), int(xy[1])), 10, (0,255,0), -1)
        else:
            tip_s=""
        hand1txt.value = "pinch %5.2f, grab %5.2f, tip %s"%(hand1.pinch_strength, hand1.grab_strength, tip_s)
    else:
        hand1txt.value = ""
    
    if  keycode == ord('q'):
        break
    elif keycode == ord(' '):
        if tip:
            screen_pos.append((int(test_pos[idx][0]*W), int(test_pos[idx][1]*H)))
            result.append((tip[0], tip[1], tip[2]))
            idx += 1
            if idx >= len(test_pos):
                idx = 0
    cv2.circle(img, (int(test_pos[idx][0]*W), int(test_pos[idx][1]*H)), 10, (0,0,255) if tip else (255,0,0), -1)
    img = cv2.flip(img, 1)
    cv2.imshow('frame', img)

    #time.sleep(0.3)
cv2.destroyWindow('frame')
cap.release()
controller.clear_policy(Leap.Controller.POLICY_BACKGROUND_FRAMES)

In [7]:
controller.enable_gesture(Leap.Gesture.TYPE_SCREEN_TAP)
controller.is_gesture_enabled(Leap.Gesture.TYPE_SCREEN_TAP)

True

In [10]:
print screen_pos

[(128, 72), (128, 360), (128, 648), (640, 72), (640, 360), (640, 648), (1152, 72), (1152, 360), (1152, 648)]


In [11]:
img.shape

(720, 1280, 3)

In [12]:
hand1.pinch_strength

1.0

In [13]:
cv2.imshow('frame', img)

In [14]:
cv2.destroyAllWindows()

In [25]:
W,H, cm0, dist0, cm, dist

(1280, 720, array([[  1.25542912e+03,   0.00000000e+00,   1.52301811e+03],
        [  0.00000000e+00,   1.23283056e+03,   8.61007986e+02],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]), array([[ 0.9896609 ,  0.96278123, -0.12145149,  0.13899587, -1.54373026]]), array([[  1.25542912e+03,   0.00000000e+00,   1.52301811e+03],
        [  0.00000000e+00,   1.23283056e+03,   8.61007986e+02],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]), array([[ 0.9896609 ,  0.96278123, -0.12145149,  0.13899587, -1.54373026]]))

In [36]:
screen_pos2 = [(W-1-x, y) for (x,y) in screen_pos]
retval, cm, dist, rvec, tvec = cv2.calibrateCamera(np.float32([result]), 
                                                   np.float32([screen_pos]), (W, H), cm0.copy(), dist0.copy(),
                                                   flags=cv2.CALIB_USE_INTRINSIC_GUESS)
print retval, rvec, tvec, cm, dist

26.8715609103 [array([[-0.26427672],
       [-0.55774494],
       [-3.00818871]])] [array([[  83.29685304],
       [ 256.72519277],
       [ 348.94659115]])] [[  1.73010332e+03   0.00000000e+00   2.47896386e+02]
 [  0.00000000e+00   1.62370067e+03   4.57490497e+02]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]] [[-1.17388728  6.16117009 -0.0321941  -0.07398026 -8.2742761 ]]


In [48]:
screen_pos2 = [(W-1-x, y) for (x,y) in screen_pos]
retval, rvec, tvec = cv2.solvePnP(np.float32([result]), 
                                                   np.float32([screen_pos]),  cm0, dist0)
cm, dist=cm0, dist0
rvec, tvec=[rvec], [tvec]
print retval, rvec, tvec, cm

True [array([[ 0.03590161],
       [-0.6163393 ],
       [-3.06629999]])] [array([[  -1.86198648],
       [ 262.13185195],
       [ 282.57265977]])] [[  1.25542912e+03   0.00000000e+00   6.39500000e+02]
 [  0.00000000e+00   1.23283056e+03   3.59500000e+02]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [63]:
print rvec, tvec, cm, dist

[array([[ 0.03590161],
       [-0.6163393 ],
       [-3.06629999]])] [array([[  -1.86198648],
       [ 262.13185195],
       [ 282.57265977]])] [[  1.25542912e+03   0.00000000e+00   6.39500000e+02]
 [  0.00000000e+00   1.23283056e+03   3.59500000e+02]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]] [[ 0.54520465 -1.47166739  0.02451086 -0.02110954  1.96975927]]


In [101]:
from math import *
def rotation(R):
    t = np.linalg.norm(R)
    u = R/t
    uu = u*u.T
    I = np.identity(3, dtype=np.float32)
    x,y,z = tuple(u.flatten())
    ux = np.float32([[0,-z,y],[z,0,-x],[-y,x,0]])
    print uu
    return cos(t)*I+(1-cos(t))*uu+sin(t)*ux
    
R=rvec[0]
print rotation(R)
print cv2.Rodrigues(R)[0]
print tvec[0], dist

[[  1.31746769e-04  -2.26175657e-03  -1.12522828e-02]
 [ -2.26175657e-03   3.88286016e-02   1.93173046e-01]
 [ -1.12522828e-02   1.93173046e-01   9.61039652e-01]]
[[-0.99964193  0.00896219 -0.02521414]
 [-0.01800878 -0.92225188  0.38616992]
 [-0.01979286  0.38648571  0.92208296]]
[[-0.9996419   0.00896219 -0.02521414]
 [-0.01800878 -0.92225185  0.38616992]
 [-0.01979286  0.38648571  0.92208299]]
[[  -1.86198648]
 [ 262.13185195]
 [ 282.57265977]] [[ 0.54520465 -1.47166739  0.02451086 -0.02110954  1.96975927]]


In [40]:
project([20,299,-20],rvec[0], tvec[0], cm, dist)

result 574.522828129 352.242077678


In [20]:

    
    
def project(p, R, T, cm, dist):
    x,y,z = tuple(np.dot(cv2.Rodrigues(R)[0], np.float32(p))+T.flatten())
    if z < 10:
        return -1,-1
    x1, y1 = x/z, y/z
    x1_2, y1_2 = x1*x1, y1*y1
    r2 = x1_2 + y1_2
    r4 = r2*r2
    r6 = r4*r2
    xy = 2*x1*y1
    k1, k2, p1, p2, k3 = tuple(dist[0])
    x2 = x1*(1+k1*r2+k2*r4+k3*r6)+p1*xy+p2*(3*x1_2+y1_2)
    y2 = y1*(1+k1*r2+k2*r4+k3*r6)+p2*xy+p1*(x1_2+3*y1_2)
    fx, fy, cx, cy = cm[0][0], cm[1][1], cm[0][2], cm[1][2]
    u, v = fx*x2+cx, fy*y2+cy 
    
    
    print "result", u, v
    pass
    
    
result2 = cv2.projectPoints(np.float32(result), rvec[0], tvec[0], cm, dist[0])[0]
for a,b,c in zip(result2, screen_pos, result):
    print a,b
    project(c, rvec[0], tvec[0], cm, dist)

NameError: name 'result' is not defined

In [41]:
retval, cm

(32.199378948556785,
 array([[  1.25542912e+03,   0.00000000e+00,  -2.51683528e+02],
        [  0.00000000e+00,   1.23283056e+03,   8.63848466e+02],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]))

In [37]:
cap = cv2.VideoCapture(0)
controller.set_policy_flags(Leap.Controller.POLICY_BACKGROUND_FRAMES)
txt = TextWidget()
txt.set_css({"width":"800px"})
display(txt)
hand1txt = TextWidget()
hand1txt.set_css({"width":"800px"})
display(hand1txt)
def to_np(v):
    return np.float32([v[0], v[1], v[2]])
def to_tuple(v):
    return ([v[0], v[1], v[2]])
while True:
    ret, img = cap.read()
    #img = cv2.resize(img, (960,540))
    H, W = img.shape[:2]
    frame = controller.frame()
    keycode = cv2.waitKey(1) & 0xff
        
    txt.value = "Frame id: %d, hands: %d, fingers: %d, tools: %d, gestures: %d" % (
              i, len(frame.hands), len(frame.fingers), len(frame.tools), len(frame.gestures()))
    tip = None
    for hand1 in frame.hands:
        for f in hand1.fingers:
            tp = f.tip_position
            xy = cv2.projectPoints(np.float32([to_np(tp)]), rvec[0], tvec[0], cm, dist)[0][0][0]
            cv2.circle(img, (int(xy[0]), int(xy[1])), 10, (0,255,0), -1)
            for bn in range(3):
                bone = f.bone(bn)
                if bone.is_valid:
                    xy1 = cv2.projectPoints(np.float32([to_np(bone.prev_joint)]), rvec[0], tvec[0], cm, dist)[0][0][0]
                    xy2 = cv2.projectPoints(np.float32([to_np(bone.next_joint)]), rvec[0], tvec[0], cm, dist)[0][0][0]
                    try:
                        cv2.line(img, tuple(xy1) , tuple(xy2), (255,255,255) , 3)
                        cv2.circle(img, tuple(xy1), 5, (255,255,128), -1)
                        cv2.circle(img, tuple(xy2), 5, (255,255,128), -1)
                    except:
                        pass
        fingers = hand1.fingers.finger_type(1)
        for f in fingers:
            tip = f.tip_position
            tip_s="(%5.1f, %5.1f, %5.1f)"%(tip[0], tip[1], tip[2])
            xy = cv2.projectPoints(np.float32([(tip[0], tip[1], tip[2])]), rvec[0], tvec[0], cm, dist)[0][0][0]
            try:
                cv2.circle(img, tuple(xy), 10, (0,0,255), -1)
            except:
                pass
        else:
            tip_s=""
        hand1txt.value = "pinch %5.2f, grab %5.2f, tip %s"%(hand1.pinch_strength, hand1.grab_strength, tip_s)
    else:
        hand1txt.value = ""
    
    if  keycode == ord('q'):
        break
    img = cv2.flip(img, 1)
    cv2.imshow('frame', img)

cv2.destroyWindow('frame')
cap.release()
controller.clear_policy(Leap.Controller.POLICY_BACKGROUND_FRAMES)

In [48]:
W,H

(1280, 720)

In [31]:
cm, dist

(array([[  1.25542912e+03,   0.00000000e+00,   1.52301811e+03],
        [  0.00000000e+00,   1.23283056e+03,   8.61007986e+02],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]]),
 array([[ 0.9896609 ,  0.96278123, -0.12145149,  0.13899587, -1.54373026]]))

In [39]:
cm1, dist1, rvec1, tvec1 = cm.copy(), dist.copy(), [tvec[0].copy()], [rvec[0].copy()]

In [46]:
tvec[0], rvec[0]

(array([[   1.37275413],
        [ 232.95848011],
        [ 227.01332068]]), array([[ 0.08543448],
        [-0.42373195],
        [-3.10790343]]))

In [40]:
print "cm="+repr(cm1)
print "dist="+repr(dist1)
print "tvec="+repr(tvec1)
print "rvec="+repr(rvec1)

cm=array([[  1.03861216e+03,   0.00000000e+00,   4.59025722e+02],
       [  0.00000000e+00,   1.00144358e+03,  -2.26439503e+01],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])
dist=array([[ 0.10414326, -0.52876669, -0.01789585,  0.00671249,  0.25075185]])
tvec=[array([[-0.15562133],
       [-1.00533923],
       [-2.89834584]])]
rvec=[array([[  18.30289231],
       [ 322.14326406],
       [ 119.28120961]])]


In [54]:
dist

array([[ 0.54520465, -1.47166739,  0.02451086, -0.02110954,  1.96975927]])

In [57]:
rvec[0]

array([[ 0.03590161],
       [-0.6163393 ],
       [-3.06629999]])

In [61]:
np.linalg.norm(rvec[0])

3.1278361002574147

In [41]:
cv2.destroyAllWindows()

In [38]:
print """
    ({r:%s, 
    t:%s, 
    k1:%s, k2:%s, k3:%s, p1:%s, p2:%s, 
    fx:%s, fy:%s, cx:%s, cy:%s})"""%(list(cv2.Rodrigues(rvec[0])[0].flatten()), 
                    list(tvec[0].flatten()),
                    dist[0][0], dist[0][1], dist[0][4], dist[0][2], dist[0][3],
                    cm[0][0], cm[1][1], cm[0][2],cm[1][2]
                    )
    
#x,y,z = tuple(np.dot(cv2.Rodrigues(R)[0], np.float32(p))+T.flatten())

#map(float, cm.flatten())



    ({r:[-0.98270474575889388, 0.10046337812322131, 0.15555864591535323, -0.038018933647139819, -0.93160560344706023, 0.36147691532153625, 0.18123449822614335, 0.34931090633146478, 0.91931275818983871], 
    t:[83.296853042942487, 256.72519276755503, 348.946591146267], 
    k1:-1.1738872833, k2:6.16117008947, k3:-8.27427609968, p1:-0.0321941000394, p2:-0.0739802556975, 
    fx:1730.10332072, fy:1623.70067172, cx:247.896386316, cy:457.490496922})


In [ ]:
project